modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "All Right Reserved"

[[mods]]
modId = "ne_zha"
version = "${version}"
displayName = "Ne Zha"
authors = "IAFEnvoy"
description = '''
This is an example description! Tell everyone what your mod is about!
'''
#logoFile = ""

[[dependencies.ne_zha]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ne_zha]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.20.2)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ne_zha]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"
